### PR TITLE
Chemsed py3compatible2

### PR DESCRIPTION
**Pull request by Permafacture**
I noticed you broke python 2 compatibility, which means you haven't been able to compare the working python2 add-delete.py to the broken python3 one. I have fixed that and made python2 use python3's map and zip to simplify discerning the difference between python 2 and 3. I suggest pulling this and using print statements rather than pdb to figure out what the difference is.

### CODE REVIEW

**Comment by Permafacture** [comment]
Let me know if you get stuck and are giving up. I have no idea how difficult a fix might be. But I got inspired and am working on another issue, and I'd like to pull a fix in the next week or two before pushing new code.

**Comment by chemsed** [comment]
I check how the all the scripts run in python 2 and 3 and I noticed these things.
I broke python compatibility by not noticing that I must add the future package in setup requirement and that unicode_literal import causes bugs. I suggest to remove the unicode_literal import as you did, but the map and zip import should be done as I made it, but with the addition of the future package. I notice that the fps are higher for both python that way and I did not find source that suggest to do it the way you did.

However, it's too soon to decide, because I'm stuck trying to make work add-delete.py in python 3. The add_some() and delete_some() doesn't work as expected. add_some clears all polygon, then add polygons, so there is only two polygons displayed. For the delete_some(), an error is raised: 
`  File "C:\Program Files (x86)\Python35-32\lib\site-packages\numpy_ecs-0.1-py3.5.egg\numpy_ecs\table.py", line 224, in rows_from_class_ids
IndexError: list index out of range`

It's been a while I look on that. I find it difficult for now. I don't say I give up, but I very clueless about that.

**Comment by Permafacture** [comment]
Sounds good. I assume the problem is in allocator.defrag which is a pretty
complicated function. Try making a copy of add_delete.py that starts with
one polygon and just calls add and one that starts with many and just calls
delete. Put prints in defrag to see what the list of guids and position
component contents look like and see where the python 2 and 3 versions
differ.

**Comment by chemsed** [comment]
How can I see the list of polygons in the allocator object?

**Comment by Permafacture** [comment]
ga._allocator.guids is a list of all the allocator guids.
ga._allocator.starts and sizes are lists of the same length of the guids
and width as names.

ie:

     allocator = ga._alloctaor
     for guid, starts, sizes in zip(allocator.guids,
allocator.statrs,allocator.sizes):
         print gui has:
         for name, start, stop in zip(ga.names,starts,sizes):
             print name is from start to start+size

**Comment by Permafacture** [comment]
Sorry, I meant allocator._allocation_table

**Pull request merged**
